- uses: actions/checkout@v3

- name: Set up Node.js
  uses: actions/setup-node@v3
  with:
    node-version: 18

- uses: jongwooo/next-cache@main

- name: Install dependencies
  run: npm ci

- name: Build
  run: npm run build
