name: Prettier source code

on:
  push:
    branches: [master]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Prettier check
        run: npx prettier --check "**/*.{tsx,jsx,ts,md,mdx}"
      - name: Prettier format
        run: npx prettier --write "**/*.{tsx,jsx,ts,md,mdx}"
